services:
  app:
    build: .
    container_name: infopalbot_app
    env_file:
      - .env
    restart: always
    volumes:
      - ./app/database:/app/app/database
    command: sh -c "alembic upgrade head && python -m app.bot.main"

networks:
  default:
    driver: bridge