"""Add category and indexes to subscription

Revision ID: 2b8b3b7b1a0a
Revises: 9edd30d5fe61
Create Date: 2025-06-30 14:15:20.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b8b3b7b1a0a'
down_revision: Union[str, Sequence[str], None] = '9edd30d5fe61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_subscription_category'), 'subscription', ['category'], unique=False)
    op.create_index(op.f('ix_subscription_details'), 'subscription', ['details'], unique=False)
    op.create_index(op.f('ix_subscription_status'), 'subscription', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_status'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_details'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_category'), table_name='subscription')
    op.drop_column('subscription', 'category')
    # ### end Alembic commands ###